version: '3.8'

services:
  backend:
    image: node-user-mysql:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=root:new-shoot@mysql:3306/new-db
    depends_on:
      - mysql
    command: sh -c "sleep 30 && npm start"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "new-shoot"
      MYSQL_DATABASE: "new-db"
      MYSQL_PASSWORD: "new-shoot"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
