version: '3.8'

services:
  backend:
    image: node-user-mysql:latest
    ports:
      - "8080:8080"
  env_file:
      - .env
    depends_on:
      - mysql
    command: sh -c "sleep 30 && npm start"

  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
